version: '2'
services:

  redis:
    container_name: hflow_redis
    image: redis:3.0

  rabbitmq:
    container_name: hflow_rabbitmq
    image: rabbitmq:3-management

  app:
    container_name: hflow_app
    depends_on:
      - redis
    build: app
    volumes:
      - ..:/code/smartscale

  executor:
    container_name: hflow_executor
    depends_on:
      - rabbitmq
      - app
    build: executor
    volumes:
      - ..:/code/smartscale
