# RabbitMQ URL, defaults to ENV['AMQP_URL']
:amqp_url: amqp://hflow_rabbitmq:5672

# Execution storage scenario: cloud | nfs | local | plgdata
# This setting may be overriden for each task
:storage: local

# Number of execution threads (defaults to: ENV['THREADS'], `nprocs` if available or 1)
:threads: <%= Executor::cpu_count %>